version: '3.8'

services:
  determined-db:
    image: postgres:14
    container_name: determined-db
    environment:
      POSTGRES_DB: determined
      POSTGRES_PASSWORD: donaldtrump
    volumes:
      - determined_db:/var/lib/postgresql/data
    networks:
      - determined-network
    ports:
      - "5432:5432"

  determined-master:
    image: determinedai/determined-master:0.37.0
    container_name: determined-master
    environment:
      DET_DB_HOST: determined-db
      DET_DB_NAME: determined
      DET_DB_PORT: 5432
      DET_DB_USER: postgres
      DET_DB_PASSWORD: donaldtrump
    ports:
      - "8080:8080"
    depends_on:
      - determined-db
    networks:
      - determined-network

  determined-agent:
    image: determinedai/determined-agent:0.37.0
    container_name: determined-agent
    environment:
      DET_MASTER_HOST: 10.178.0.3
      DET_MASTER_PORT: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - determined-master
    networks:
      - determined-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  determined_db:

networks:
  determined-network:
    driver: bridge
